# This file was generated by Johny Appleseed

import os

print("{{message}}")


def foo_bar2():
    """This is a sample fuction.

    Lorum Ipsum
    """
    raise NotImplementedError()


def bar3(id):
    return f"{id}!!!!"