import os

from typing import Sequence


def _write_header(f):
    header = "# This file was generated by Appleseed"
    f.write(header + '\n')


class AppleseedContext:
    def __init__(self, console, parameters):
        self.console = console
        self.parameters = parameters
        self.files_written = []

    def write_file(self, paths: Sequence[str], content: str):

        # Make sure all directories exist for this file
        for i, _ in enumerate(paths):
            try:
                if paths[:i]:
                    os.mkdir(os.path.join(*paths[:i]))
            except OSError:
                pass

        with open(os.path.join(*paths), 'w') as output:
            _write_header(output)
            output.write(content)
        self.files_written.append(os.path.join(*paths))